
RESPONSE_MESSAGE = {
    "success.code.continue": "CONTINUE",
    "success.code.switch": "SWITCHING_PROTOCOLS",
    "success.code.not_minor": "NOT_MINOR",
    "success.code.ok": "OK",
    "success.code.created": "CREATED",
    "success.code.accepted": "ACCEPTED",
    "error.code.user_exists": "USER_EXISTS",
    "error.code.socialtoken": "INVALID_TOKEN_FROM_SERVICE_PROVIDER",
    "error.code.minor": "MINOR",
    "error.code.already_active": "USER_ALREADY_ACTIVE",
    "error.code.trad_user_exists": "TRADITIONAL_USER_EXISTS",
    "error.code.not_found": "NOT_FOUND"
}

RESPONSE_CODE = {
    "success.code.continue": 100,
    "success.code.switch": 101,
    "success.code.not_minor": 102,
    "success.code.ok": 200,
    "success.code.created": 201,
    "success.code.accepted": 202,
    "error.code.user_exists": 207,
    "error.code.socialtoken": 208,
    "error.code.minor": 209,
    "error.code.already_active": 210,
    "error.code.trad_user_exists": 217,
    "error.code.not_found": 404
}

REQUEST_METHOD = {'POST': 'POST', 'GET': 'GET', 'PUT': 'PUT', }

ERROR_MESSAGE = {
    "error.code.nai": "NON_AUTHORITATIVE_INFORMATION",
    "error.code.no_content": "NO_CONTENT",
    "error.code.reset_content": "RESET_CONTENT",
    "error.code.partial_content": "PARTIAL_CONTENT",
    "error.code.user_exists": "USER_EXISTS",
    "error.code.socialtoken": "INVALID_TOKEN_FROM_SERVICE_PROVIDER",
    "error.code.minor": "MINOR",
    "error.code.already_active": "USER_ALREADY_ACTIVE",
    "error.code.invalidmail": "INVALID_EMAIL_ADDRESS",
    "error.code.inactiveuser": "INACTIVE_USER",
    "error.code.banned": "BANNED_USER",
    "error.code.locked": "USER_LOCKED",
    "error.code.password": "WRONG_PASSWORD",
    "error.code.suspended": "SUSPENEDED_USER",
    "error.code.trad_user_exists": "TRADITIONAL_USER_EXISTS",
    "error.code.flagged_post": "FLAGGED POST",
    "error.code.unflagable_post_type": "UNFLAGABLE_POST_TYPE",
    "error.code.already_voted_flag": "ALREADY_VOTED_FLAG",
    "error.code.exceed_vote_count": "EXCEED_VOTE_COUNT",
    "error.code.expired_vote": "EXPIRED_VOTE",
    "error.code.friends_request_withdrawed": "FRIENDS_REQUEST_WITHDRAWED",
    "error.code.relation_already_exists": "RELATION_ALREADY_EXISTS",
    "error.code.invalid_parameter_value": "INVALID_PARAMETER_VALUE",
    "error.code.not_enough_gives": "NOT_ENOUGH_GIVES",
    "error.code.permission_denined": "PERMISSION_DENIED",
    "error.code.bad_request": "BAD_REQUEST",
    "error.code.unauthorized": "UNAUTHORIZED",
    "error.code.payment_reqd": "PAYMENT_REQUIRED",
    "error.code.forbidden": "FORBIDDEN",
    "error.code.not_found": "NOT_FOUND",
    "error.code.method_not_allowed": "METHOD_NOT_ALLOWED",
    "error.code.not_accept": "NOT_ACCEPTABLE",
    "error.code.proxy_auth_reqd": "PROXY_AUTHENTICATION_REQUIRED",
    "error.code.timeout": "REQUEST_TIMEOUT",
    "error.code.internal_server_error": "INTERNAL_SERVER_ERROR",
    "error.code.db_error": "DATA_BASE_ERROR"
}

ERROR_CODE = {
    "error.code.nai": 203,
    "error.code.no_content": 204,
    "error.code.reset_content": 205,
    "error.code.partial_content": 206,
    "error.code.user_exists": 207,
    "error.code.socialtoken": 208,
    "error.code.minor": 209,
    "error.code.already_active": 210,
    "error.code.invalidmail": 211,
    "error.code.inactiveuser": 212,
    "error.code.banned": 213,
    "error.code.locked": 214,
    "error.code.password": 215,
    "error.code.suspended": 216,
    "error.code.trad_user_exists": 217,
    "error.code.flagged_post": 218,
    "error.code.unflagable_post_type": 219,
    "error.code.already_voted_flag": 220,
    "error.code.exceed_vote_count": 221,
    "error.code.expired_vote": 222,
    "error.code.friends_request_withdrawed": 223,
    "error.code.relation_already_exists": 224,
    "error.code.invalid_parameter_value": 225,
    "error.code.not_enough_gives": 226,
    "error.code.permission_denined": 227,
    "error.code.bad_request": 400,
    "error.code.unauthorized": 401,
    "error.code.payment_reqd": 402,
    "error.code.forbidden": 403,
    "error.code.not_found": 404,
    "error.code.method_not_allowed": 405,
    "error.code.not_accept": 406,
    "error.code.proxy_auth_reqd": 407,
    "error.code.timeout": 408,
    "error.code.internal_server_errror": 500,
    "error.code.db_error": 507
}

RESPONSE_MESSAGES_DICT = {
    "SUCCESS_CONTINUE": "CONTINUE",
    101: "SWITCHING_PROTOCOLS",
    102: "NOT_MINOR",
    200: "OK",
    201: "CREATED",
    202: "ACCEPTED",
    203: "NON_AUTHORITATIVE_INFORMATION",
    204: "NO_CONTENT",
    205: "RESET_CONTENT",
    206: "PARTIAL_CONTENT",
    207: "USER_EXISTS",
    208: "INVALID_TOKEN_FROM_SERVICE_PROVIDER",
    209: "MINOR",
    210: "USER_ALREADY_ACTIVE",
    211: "INVALID_EMAIL_ADDRESS",
    212: "INACTIVE_USER",
    213: "BANNED_USER",
    214: "USER_LOCKED",
    215: "WRONG_PASSWORD",
    216: "SUSPENDED_USER",
    217: "TRADITIONAL_USER_EXISTS",
    218: "FLAGGED_POST",
    219: "UNFLAGABLE_POST_TYPE",
    220: "ALREADY_VOTED_FLAG",
    221: "EXCEED_VOTE_COUNT",
    222: "EXPIRED_VOTE",
    223: "FRIENDS_REQUEST_WITHDRAWED",
    224: "RELATION_ALREADY_EXISTS",
    225: "INVALID_PARAMETER_VALUE",
    226: "NOT_ENOUGH_GIVES",
    227: "PERMISSION_DENIED",
    400: "BAD_REQUEST",
    401: "UNAUTHORIZED",
    402: "PAYMENT_REQUIRED",
    403: "FORBIDDEN",
    404: "NOT_FOUND",
    405: "METHOD_NOT_ALLOWED",
    406: "NOT_ACCEPTABLE",
    407: "PROXY_AUTHENTICATION_REQUIRED",
    408: "REQUEST_TIMEOUT",
    414: "REQUEST_URI_TOO_LONG",
    415: "UNSUPPORTED_MEDIA_TYPE",
    428: "PRECONDITION_REQUIRED",
    431: "REQUEST_HEADER_FIELDS_TOO_LARGE",
    500: "INTERNAL_SERVER_ERROR",
    501: "NOT_IMPLEMENTED",
    502: "BAD_GATEWAY",
    503: "SERVICE_UNAVAILABLE",
    504: "GATEWAY_TIMEOUT",
    505: "VERSION_NOT_SUPPORTED",
    506: "AUTHENTICATION_REQUIRED",
    507: "DB_CONNECT_ERROR"
}
